version: '3.4'

services:
  gpt-content-audit:
    image: deanxv/gpt-content-audit:latest
    container_name: gpt-content-audit
    restart: always
    ports:
      - "7088:7088"
    volumes:
      - ./data:/app/gpt-content-audit/data
    environment:
      - AUDIT_TYPE=ali
      - BASE_URL=https://example.com
      - AUTHORIZATION=123456
      - TZ=Asia/Shanghai